const MAX_LENGTH_RATIO = 1.25;
const NUM_RELEVANT_ELEMENTS = 6;
const MIN_IN_CLUSTER = 3;
const MIN_THRESHOLD = 0.5;

module.exports = { MAX_LENGTH_RATIO, NUM_RELEVANT_ELEMENTS, MIN_IN_CLUSTER, MIN_THRESHOLD };